project:
  type: website
  output-dir: docs

resources:
  - Saturdata/TreeLesson_WS.pdf

website:
  title: "DS4HS"
  navbar:
    logo: Saturdata/DS4HS.png
    pinned: true
    collapse: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Curriculum"
        menu:
          - text: "Tree Equity Lesson"
            href: Saturdata/TreeLesson.qmd
          - text: "Public Transportation Lesson"
            href: Saturdata/PublicTransportLesson.qmd
      - text: "Instructor Materials"
        menu:
          - text: "Tree Equity Guide"
            href: Saturdata/TLNotes.qmd
      - text: "Contact"

format:
  html:
    theme: cosmo
    css: Saturdata/custom_theme.css
    toc: false