project:
  type: website
  output-dir: docs

website:
  title: "DS4HS"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    css: styles.css
    toc: true


