project:
  type: website
  output-dir: docs

resources:
  - Saturdata/TES/TreeLesson_WS.pdf

website:
  title: "DS4HS"
  navbar:
    logo: Saturdata/images/DS4HS.png
    pinned: true
    collapse: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Curriculum"
        menu:
          - text: "Tree Equity Lesson"
            href: Saturdata/TES/TreeLesson.qmd
          - text: "Public Transportation Lesson"
            href: Saturdata/Transit/PublicTransportLesson.qmd
      - text: "Instructor Materials"
        menu:
          - text: "Tree Equity Guide"
            href: Saturdata/TES/TLNotes.qmd
          - text: "Public Transit Guide"
            href: Saturdata/Transit/PTNotes.qmd
      - text: "Contact"

format:
  html:
    theme: cosmo
    css: custom_theme.css
    toc: false